version: '3'
services:
  blog:
    build: .
    image: my-django-app:latest
    command: python manage.py runserver 0.0.0.0:6800
    ports:
      - '${SPP_PORT:-6800}:6800'
    networks:
      - blog
    depends_on:
      - db

  db:
    image: mysql:8.0.30
    container_name: db-blog-app
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - '/docker-dbs/blog:/var/lib'
    networks:
      - blog
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

  adminer:
    image: adminer
    container_name: adminer-blog-app
    ports:
      - '${FORWARD_ADMINER_PORT:-8080}:8080'
    networks:
      - blog

networks:
  blog:
    driver: bridge
